// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["underscore", "backbone"], function(_, Backbone) {
    var TodoModel;
    return TodoModel = (function(_super) {

      __extends(TodoModel, _super);

      function TodoModel() {
        console.log("new TodoModel");
        TodoModel.__super__.constructor.apply(this, arguments);
      }

      TodoModel.prototype.defaults = {
        title: "",
        completed: false,
        rating: 0
      };

      TodoModel.prototype.toggle = function() {
        this.save({
          completed: !this.get("completed"),
          rating: 1
        });
        return console.log("saved " + (this.get('id')));
      };

      return TodoModel;

    })(Backbone.Model);
  });

}).call(this);
