// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["jquery", "backbone", "common"], function($, Backbone, Common) {
    var TodoRouter;
    return TodoRouter = (function(_super) {

      __extends(TodoRouter, _super);

      function TodoRouter(todos) {
        this.todos = todos;
        this.setFilter = __bind(this.setFilter, this);

        TodoRouter.__super__.constructor.apply(this, arguments);
      }

      TodoRouter.prototype.routes = {
        "*filter": "setFilter"
      };

      TodoRouter.prototype.setFilter = function(param) {
        Common.TodoFilter = param.trim() || "";
        return this.todos.trigger("filter");
      };

      return TodoRouter;

    })(Backbone.Router);
  });

}).call(this);
