// Generated by CoffeeScript 1.3.3
(function() {

  define(["jquery", "backbone", "collections/TodosCollection", "common"], function($, Backbone, Todos, Common) {
    var Router;
    return Router = Backbone.Router.extend({
      routes: {
        "*filter": "setFilter"
      },
      setFilter: function(param) {
        Common.TodoFilter = param.trim() || "";
        return Todos.trigger("filter");
      }
    });
  });

}).call(this);
