// Generated by CoffeeScript 1.3.3
(function() {

  define(["underscore", "backbone", "views/AppView", "routers/TodoRouter", "collections/TodosCollection"], function(_, Backbone, AppView, Router, TodosCollection) {
    var todos;
    todos = new TodosCollection;
    new AppView(todos);
    new Router(todos);
    Backbone.history.start();
    return null;
  });

}).call(this);
