// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["jquery", "underscore", "backbone", "views/TodoView", "text!../../templates/stats.html", "common"], function($, _, Backbone, TodoView, statsTemplate, Common) {
    var AppView;
    return AppView = (function(_super) {

      __extends(AppView, _super);

      function AppView(todos) {
        this.todos = todos;
        this.filterAll = __bind(this.filterAll, this);

        this.addAll = __bind(this.addAll, this);

        this.addOne = __bind(this.addOne, this);

        this.render = __bind(this.render, this);

        console.log("new AppView");
        AppView.__super__.constructor.apply(this, arguments);
      }

      AppView.prototype.el = "#todoapp";

      AppView.prototype.template = _.template(statsTemplate);

      AppView.prototype.events = {
        "keypress #new-todo": "createOnEnter",
        "click #clear-completed": "clearCompleted",
        "click #toggle-all": "toggleAllComplete"
      };

      AppView.prototype.initialize = function() {
        this.input = this.$("#new-todo");
        this.allCheckbox = this.$("#toggle-all")[0];
        this.$footer = this.$("#footer");
        this.$main = this.$("#main");
        this.todos.on("add", this.addOne);
        this.todos.on("reset", this.addAll);
        this.todos.on("change:completed", this.filterOne);
        this.todos.on("filter", this.filterAll);
        this.todos.on("all", this.render);
        return this.todos.fetch();
      };

      AppView.prototype.render = function() {
        var completedCount, remainingCount;
        completedCount = this.todos.completed().length;
        remainingCount = this.todos.remaining().length;
        if (this.todos.length) {
          this.$main.show();
          this.$footer.show();
          this.$footer.html(this.template({
            completed: completedCount,
            remaining: remainingCount
          }));
          this.$("#filters li a").removeClass("selected").filter("[href=\"#/" + (Common.TodoFilter || "") + "\"]").addClass("selected");
        } else {
          this.$main.hide();
          this.$footer.hide();
        }
        return this.allCheckbox.checked = !remainingCount;
      };

      AppView.prototype.addOne = function(todo) {
        var view;
        view = new TodoView({
          model: todo
        });
        return $("#todo-list").append(view.render().el);
      };

      AppView.prototype.addAll = function() {
        console.log("addAll");
        this.$("#todo-list").html("");
        return this.todos.each(this.addOne, this);
      };

      AppView.prototype.filterOne = function(todo) {
        return todo.trigger("visible");
      };

      AppView.prototype.filterAll = function() {
        return this.todos.each(this.filterOne, this);
      };

      AppView.prototype.newAttributes = function() {
        return {
          title: this.input.val().trim(),
          order: this.todos.nextOrder(),
          completed: false,
          rating: 0
        };
      };

      AppView.prototype.createOnEnter = function(e) {
        if (e.which !== Common.ENTER_KEY || !this.input.val().trim()) {
          return;
        }
        this.todos.create(this.newAttributes());
        return this.input.val("");
      };

      AppView.prototype.clearCompleted = function() {
        _.each(this.todos.completed(), function(todo) {
          return todo.destroy();
        });
        return false;
      };

      AppView.prototype.toggleAllComplete = function() {
        var completed;
        completed = this.allCheckbox.checked;
        return this.todos.each(function(todo) {
          return todo.save({
            completed: completed
          });
        });
      };

      return AppView;

    })(Backbone.View);
  });

}).call(this);
