// Generated by CoffeeScript 1.3.3
(function() {

  define(["underscore", "backbone", "views/AppView", "routers/Router", "collections/TodosCollection"], function(_, Backbone, AppView, Router, TodosCollection) {
    new AppView;
    new Router;
    Backbone.history.start();
    return null;
  });

}).call(this);
