// Generated by CoffeeScript 1.3.3
(function() {

  require.config({
    baseUrl: "",
    shim: {
      underscore: {
        exports: "_"
      },
      backbone: {
        deps: ["underscore", "jquery"],
        exports: "Backbone"
      }
    },
    paths: {
      jquery: "lib/jquery/jquery.min",
      underscore: "lib/underscore/underscore",
      backbone: "lib/backbone/backbone",
      text: "lib/require/text"
    }
  });

  require(["js/views/AppView", "js/routers/Router"], function(AppView, Router) {
    new AppView();
    new Router();
    return Backbone.history.start();
  });

}).call(this);
